### ISSUE TITLE
error during suricata object creation

### ISSUE THREAD

**Issue by garanews** [MISP/misp-objects#106]
![immagine](https://user-images.githubusercontent.com/16938405/42086681-283b70aa-7b94-11e8-988c-9e94f7951f43.png)

**Comment by garanews** [comment]
with git pull origin 2.4 and git submodule update --init --force still receiving old file

**Comment by adulau** [comment]
Thanks for the feedback. Fixed in https://github.com/MISP/MISP/commit/87d429511950c72deb41577d00bf9a9ac94445b5 - git pull and git submodule update again ;-)

**Comment by garanews** [comment]
OK, now works.
Thanks to you.
