### ISSUE TITLE
Allow multiple domains in domain|ip object

### ISSUE THREAD

**Issue by jipegit** [MISP/misp-objects#108]
Allow multiple domains in domain|ip object

**Comment by cvandeplas** [comment]
Can you give some examples where it could be relevant to have multiple domains in one object?
With shared hosting one IP can hold multiple domains, but why do you think this should be grouped in one single object? 
Thanks

**Comment by adulau** [comment]
I see some cases where multiple domains pointing to a single IP address (and not willing to use the passive dns objects). I fixed the object template.

**Comment by jipegit** [comment]
Thanks!
