### ISSUE TITLE
Cortex Object?

### ISSUE THREAD

**Issue by andurin** [MISP/misp-objects#128]
Hi,

so the world is using MISP, TheHive, Cortex and Co. 
Would it make sense to have a Cortex Object containing values, taxonomies and so on?

If someone else need this I would prepare a PR for this.

Regards

**Comment by adulau** [comment]
Here is a first version based on a discussion with @jeromeleonard  https://github.com/MISP/misp-objects/commit/39dd150e2a85b2b5a041a202343ecefa4d34b43a
