### ISSUE TITLE
Netflow v5/v9 object

### ISSUE THREAD

**Issue by adulau** [MISP/misp-objects#13]
Netflow v5/v9 object

**Comment by JanKoDFNCERT** [comment]
Hi Alexandre,

I uploaded a first proposal for a netflow object
[definition.json.txt](https://github.com/MISP/misp-objects/files/1382483/definition.json.txt)

**Comment by adulau** [comment]
Great! Thank you very much. 

I just did a commit of your proposal with some notes in the commit message:

https://github.com/MISP/misp-objects/commit/94b9bc9aee06a446573f6fc2e5cfe60b105ce056

It's already a good basis.

**Comment by adulau** [comment]
Netflow object template is present.
