### ISSUE TITLE
Person object - missing fields? 

### ISSUE THREAD

**Issue by Delta-Sierra** [MISP/misp-objects#132]
Hi,
I was wondering if it could be interresting to add field in person object template to match this document:
![screenshot from 2018-12-04 12-13-58](https://user-images.githubusercontent.com/17081497/49438463-b35f1500-f7be-11e8-98f7-47ce0de2fd82.png)
Source: https://sanctionssearch.ofac.treas.gov/Details.aspx?id=7344

**Comment by adulau** [comment]
Fixed in 11a462e79b02428a08b11698d45aa8aa5ab6887d thank you.
