### ISSUE TITLE
Cowrie, script, & ip-port objects - required attributes

### ISSUE THREAD

**Issue by alinamd** [MISP/misp-objects#149]
Please consider updating the following: 

cowrie object: add honeypot name as a possible required field
- The cowrie honeypot object template requires session attribute, I don't have the session ID but I have the honeypot name.

Script object: add filename as a possible required field (Required one of:)
- The script object only contains 1 required attribute, the script attribute (free text of the script). I don't have the shell script but I know the script filename.

IP-port object: add ip-src attribute to this object
- The ip-port object contains dst-port, ip-dst, src-port, but no ip-src field

**Comment by adulau** [comment]
For the cowrie object, the field `sensor` is the honeypot name.

I fixed the script object and the ip-port object. Good point. Thank you for the feedback.
