### ISSUE TITLE
HTTP header object (based on the referer case)

### ISSUE THREAD

**Issue by adulau** [MISP/misp-objects#16]
HTTP header object (based on the referer case)

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

**Comment by infosec-intern** [comment]
I'd love to take this on. Would it make more sense to have separate http-request and http-response objects instead of one http-header object?

**Comment by adulau** [comment]
I think the header case is when analysts got the header (e.g. from reversing, static analysis or other means) without having the http-request or http-response directly. So this can be alone too.

But you are right, a http-request and http-response templates are actively needed. Feel free to make a PR and I'll have a look.

**Comment by Rafiot** [comment]
Fixed by: https://github.com/MISP/misp-objects/pull/17
