### ISSUE TITLE
# buggy file object

### ISSUE THREAD

**Issue by haxpak** [MISP/misp-objects#175]
# trying to upload a file as malware-sample in object "file" is not accepted by the server
- the file object has an attribute malware sample which has a misp-attribute as malware-sample.
- the same needs to be changed to attachment as the Model for the misp attribute "malware-sample" requires a composite value, which is not auto generated when uploading a sample using the file object

# solution
- change attribute type of malware-sample to "attachment". 
- not rename the attribute "malware-sample" to retain backward compatibility

# if accepted, i will do the needful

**Comment by iglocska** [comment]
Malware sample is correct, the behavior is incorrect however. I'll look into fixing it.

**Comment by Rafiot** [comment]
@haxpak how do you upload the malware-sample in object "file"?
