### ISSUE TITLE
Authenticode

### ISSUE THREAD

**Issue by chrisr3d** [MISP/misp-objects#180]
"signature": {
          "signed": true,
          "subjectchain": "CN=Simon Tatham, O=Simon Tatham, L=Cambridge, S=Cambridgeshire, C=GB\n",
          "sigissuer": "CN=COMODO SHA-256 Code Signing CA, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB\n",
          "version": "3\n",
          "bachain": "12/10/2015 1:00:00 AM\n 12/2/2018 12:59:59 AM\n",
          "thumbprint": "4022BB3C0398D595623A5380D5EEB520FC6150AA\n",
          "thumbprintMD5": "78989302406896B6DC127192D368F10D\n",
          "thumbprintSHA256": "028AE2E1053D8383B36F34EF81CD5E554ED462BAA1037C621FE891BB2D60C41B\n",
          "serial": "6CD282A2D9A2C158505B178D59518B7B\n",
          "sigvalid": "true\n",
          "errornbr": "0\n",
          "sigerror": "The operation completed successfully\n"
        }

**Comment by Rafiot** [comment]
https://lief.quarkslab.com/doc/latest/api/python/pe.html#x509

**Comment by adulau** [comment]
I just fixed the existing x509 MISP object to support the required fields needed from the authenticode decoding from LIEF. So we can used this object and use the [relationship type](https://www.misp-project.org/objects.html#_relationships) `signed-by` with the corresponding PE.

![windows-authenticode](https://user-images.githubusercontent.com/3309/57192714-a8f2a400-6f33-11e9-8fe1-b1dad2b15b99.png)

For the remaining part, I propose to create 2 new object template (especially to see correlation between specific cut-and-paste signatures) one is `authenticode-contentInfo` and `authenticode-signerInfo`.  @Rafiot let me know if this is fine for you. 

For the tests, we would need a set of PE signed with authenticode. Maybe we could use [this script](https://github.com/mtrojnar/osslsigncode/blob/master/tests/testsign.sh) to generate the various test cases.

**Comment by adulau** [comment]
Fixed with 1e14201fc03dd93a78e645a478be5c842be2097c
