### ISSUE TITLE
Some links on https://www.misp-project.org/objects.html do not work

### ISSUE THREAD

**Issue by wagner-certat** [MISP/misp-objects#218]
Hi,

https://www.misp-project.org/objects.html shows the templates, but it seems some of the "this location" links are broken. The tsk-* ones where renamed to capital letters, but the webpage shows the lower case variants.

**Comment by adulau** [comment]
Thank you. I'll have a look.

**Comment by adulau** [comment]
This has been fixed sometime ago. I forgot to close the issue.
