### ISSUE TITLE
Comon name for the security code of a credit card is CVV (Card Verification Value)

### ISSUE THREAD

**Issue by Rafiot** [MISP/misp-objects#23]
Most of the vendors will call he security code CVV (i.e. Amazon: https://www.amazon.in/gp/help/customer/display.html?nodeId=201461830), so it might be good to rename it: https://github.com/MISP/misp-objects/blob/777ef97aebef19eb09b24a4342ff62bc7318e478/objects/credit-card/definition.json#L16

What do you think?

**Comment by adulau** [comment]
card-security-code is quite generic and includes CSC, CVD, CVV, CVC and SPC.

**Comment by Rafiot** [comment]
okay, works, I'll just update the description.

**Comment by adulau** [comment]
@Rafiot Thank you!
