### ISSUE TITLE
Where is the license file?

### ISSUE THREAD

**Issue by joachimmetz** [MISP/misp-objects#266]
Per README:

```
You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

Where is this file?

**Comment by adulau** [comment]
It's more the software used for the tests and so on. The JSON can be licensed to something really laxed. What would be the best for the template ? Simplified BSD License ? Thanks

**Comment by joachimmetz** [comment]
That is a separate issue, I'm not a lawyer, but seeing these schemas are based on the MISP project it might not be possible to re-license them. At the moment the project is not complying to its own license.

**Comment by joachimmetz** [comment]
Also see: https://www.gnu.org/licenses/gpl-howto.en.html
