### ISSUE TITLE
Add support to JA3s

### ISSUE THREAD

**Issue by jgvt** [MISP/misp-objects#296]
Hello,

It may be useful to add support to JA3S to MISP with the same format that JA3 which is already implemented :

attributes, first-seen, ip-dst, ip-src, ja3-fingerprint-md5, ja3s-fingerprint-md5, last-seen.

[ja3s-definition.json.txt](https://github.com/MISP/misp-objects/files/5281496/ja3s-definition.json.txt)

**Comment by adulau** [comment]
Thank you for the contribution. It's now in the default object template repository. (sorry I missed your contribution as it was not a pull-request)
