### ISSUE TITLE
New object for RTIR ticket

### ISSUE THREAD

**Issue by adulau** [MISP/misp-objects#32]
New object for RTIR ticket

**Comment by michael-hamm** [comment]
Random ideas:
1.  There should be important meta data describing the ticket: (Ticket Number, Subject, Status, Constituency, Classification and queue (Incident, Investigation, ...)).
2. A ticket can consists out of multiple single messages and other related tickets. It could be worth to support this relations.
3. The message content could consist out of text including IOCs which are may worth to get recognized, and probably attachments.
4. if custom fields should be supported they must be configured in JSON files.

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/misp-objects/commit/2b9ba3ac00060948b03a281fa176982dad56d999
