### ISSUE TITLE
RAT config object?

### ISSUE THREAD

**Issue by adulau** [MISP/misp-objects#35]
RAT config object? Following the talk from @bambenek, we might need a generic misp-object for the RAT or malware configuration. 

The idea is to store the JSON in that object but we might need some metadata. @bambenek do you see the required metadata which would be needed?

**Comment by geekscrapy** [comment]
Is this not covered here?
https://github.com/MISP/misp-objects/blob/master/objects/malware-config/definition.json

**Comment by adulau** [comment]
Indeed good point. It was fixed.
