### ISSUE TITLE
Fail2Ban object (v5) has invalid RFC 4122 UUID

### ISSUE THREAD

**Issue by aacgood** [MISP/misp-objects#377]
## Issue

Version 5 of the Fail2Ban object has an invalid RFC 4122 UUID and as a result you cannot save an object with this template
![image](https://user-images.githubusercontent.com/28122532/205561259-f2b97ef4-efbf-4cfb-aaf8-f95dba57d089.png)

## Potential Fix

Update `misp-objects/objects/fail2ban/definition.json` with a RFC4122 compliant UUID and increment version number.

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/misp-objects/commit/d491cde4b15d25725fafbc37fa7f8d69178fa1ed.
