### ISSUE TITLE
Add scanner and scanner-query to network-profile object

### ISSUE THREAD

**Issue by mFaou** [MISP/misp-objects#390]
Hello,
I'd like to enrich the network-profile object with two attributes:

- scanner: it would be a string from the following list shodan, censys, zoomeye, onyphe, binaryedge
- scanner-query: it would contain a query (as a string) in the language of the selected scanner

Do you think it's a good idea to add those two fields in the network-profile object or it would be better to create a new object? Once it is decided, I can do a PR.

Thanks.

**Comment by mFaou** [comment]
@adulau, any opinion on this?

**Comment by mokaddem** [comment]
Hello,
Instead of modifying `network-profile` objects, what do you think of updating [`scan-result`](https://github.com/MISP/misp-objects/blob/main/objects/scan-result/definition.json) instead?

**Comment by mFaou** [comment]
good idea. And can I add shodan, censys, etc in the scan-result-tool list?

**Comment by mFaou** [comment]
PR: https://github.com/MISP/misp-objects/pull/401

**Comment by mFaou** [comment]
FYI: https://github.com/MISP/misp-objects/pull/402
We'd like to be able to use the object to store the scan-result-query without necessarily attaching a file. For example we will create additional domain-ip objects and link them to this scan-result object.

**Comment by mFaou** [comment]
Thanks for the merge and release, I'm closing the ticket
