### ISSUE TITLE
password brute-force object to add

### ISSUE THREAD

**Issue by adulau** [MISP/misp-objects#44]
password brute-force object to add

**Comment by adulau** [comment]
After some discussions, it seems that a generic password object will make sense with a type (brute-force, hard coded in malware, key,...).

**Comment by iglocska** [comment]
Or a credential object? To also include username, apikey etc as optional
values?

**Comment by iglocska** [comment]
Perhaps change the values in "origin" to a sane default list?

**Comment by adulau** [comment]
Good point. It's fixed https://github.com/MISP/misp-objects/commit/2a2b48a162fc94989209115fb19e00ac8e8f1ce1
