### ISSUE TITLE
Extend whois object + misp attributes

### ISSUE THREAD

**Issue by c-goes** [MISP/misp-objects#55]
1. add new misp attribute `whois-registrant-org` (used by domaintools for example)
2. add new object relation to whois field `registrant-org`
3. rename `registant` to `registrant` in whois object

**Comment by adulau** [comment]
@c-goes Thank you for the issue. Just a small question, where have you seen the typo registant? I cannot find it in the current revision of the whois object.

**Comment by c-goes** [comment]
I meant registar, sorry
https://github.com/MISP/misp-objects/blob/master/objects/whois/definition.json#L18

**Comment by adulau** [comment]
Good catch! Fixed in 04d38118d1626145ceabed5afbbc17313e5f8b27 

I keep it open until we update the MISP attribute.

**Comment by adulau** [comment]
It's now fixed in MISP https://github.com/MISP/MISP/commit/3c4d8f53ee1769d5d6de4e166d7ace589f9c5d03 and MISP whois object updated to include registrant-org. Let us know if you have any issues. Cheers.
