### ISSUE TITLE
x509 attribute types are different than normal attribute types

### ISSUE THREAD

**Issue by cvandeplas** [MISP/misp-objects#59]
An existing attribute type is ```x509-fingerprint-sha1```, however the x509 misp object defines the ```misp-attribute``` as ```md5```, ```sha1```, ```sha256```.

This has 2 downsides:
1. searching for attibute types like ```x509-fingerprint-sha1``` (PyMISP and webinterface) will not return x509 misp-object attributes
2. a dump of (any) md5, sha1, sha256 which are everywhere else used for filenames, will als contain hashes related to x509 certificates; which is illogical

The proposal is thus to change the x509 object type to the
1. already existing ```x509-fingerprint-sha1```
2. newly created ```x509-fingerprint-md5```, and ```x509-fingerprint-sha256```

What do you think?

**Comment by adulau** [comment]
Fixed in b85438fc45b212a21b72d6d2e0df619758fa1444 and https://github.com/MISP/MISP/commit/bab083b345f8ba7e897a91a3fdba12e381edfd7a.

Cheers
