### ISSUE TITLE
MapSmsTP-DCS value set to 0 is considered as empty value

### ISSUE THREAD

**Issue by yodresh** [MISP/misp-objects#91]
In the object [Ss7-attack](https://github.com/MISP/misp-objects/blob/master/objects/ss7-attack/definition.json) when I try to add a TP-DCS with value 0, MISP is returning the following error:
> Could not save object as at least one attribute has failed validation (MapSmsTP-DCS). {"value":["Value cannot be empty."]}

![image](https://user-images.githubusercontent.com/1607556/38495547-4a9b4d48-3bfa-11e8-80bb-1a3ad000a283.png)
Category selected is "Other" by default for the field.

When I validate the object without the field then try to edit it again to add MapSmsTP-DCS with value 0, no error is displayed but the field addition is silently dropped.

**Comment by adulau** [comment]
Very good catch! https://github.com/MISP/MISP/commit/025b2a4e5daffe805f3ae41e87d3f1e9c367805d 

It's also updated on misptelco ;-) Let us know if this is fine.

**Comment by yodresh** [comment]
Just tested on [misptelco](https://misptelco.circl.lu/events/view/37) and bug seems to be fixed !
Thanks :)

**Comment by adulau** [comment]
Great. Thank you for the finding.
